### ISSUE TITLE
Not accessible

### ISSUE THREAD

**Issue by aaronychu** [mziech/nextcloud-cas#16]
Nextcloud Version: `27.1.2 RC1`
When access the base URL `{NEXTCLOUD URL}/apps/cas/`, the page says `Forbidden - You don't have permission to access this resource.`
When acces an login URL `{NEXTCLOUD URL}/apps/cas/login?server={URL}`, the page says `Not Found - The requested URL was not found on this server.`

**Comment by mziech** [comment]
Hi!
1. The login URL should be with parameter **service**: `{NEXTCLOUD URL}/apps/cas/login?service={URL}`
2. Did you configure a CAS service in the admin security settings before logging in?

**Comment by mziech** [comment]
... timeout
