### ISSUE TITLE
Column "oc_cas_ticket"."service" is type String, but exceeding the 4.000 length limit.

### ISSUE THREAD

**Issue by mv-stns** [mziech/nextcloud-cas#8]
# Cant enable CAS Server

Error:

```zsh
Column "oc_cas_ticket"."service" is type String, but exceeding the 4.000 length limit.
```

### Steps to reproduce

Try install CAS Server & enable it

### Expected behavior

Should just be enabled and work

### Installation method

Via cli with
```zsh
php occ app:install cas
```

Or just via Settings > Apps > CAS Server > Install & Enable

### Nextcloud Version

24.0

### Operating system

Ubuntu 20.04/ Plesk

### PHP version

PHP 8.1

### Web server

NGINX

### Database engine version

mysql  Ver 15.1 Distrib 10.3.34-MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Install

### Are you using the Nextcloud Server Encryption module?

Yes

### List of activated Apps

- [x] accessibility: 1.10.0
- [x] activity: 2.16.0
- [x] admin_audit: 1.14.0
- [x] announcementcenter: 6.2.0
- [x] bruteforcesettings: 2.4.0
- [x] circles: 24.0.0
- [x] cloud_federation_api: 1.7.0
- [x] comments: 1.14.0
- [x] contactsinteraction: 1.5.0
- [x] dashboard: 7.4.0
- [x] dav: 1.22.0
- [x] deck: 1.7.0
- [x] encryption: 2.12.0
- [x] federatedfilesharing: 1.14.0
- [x] federation: 1.14.0
- [x] files: 1.19.0
- [x] files_downloadactivity: 1.13.0
- [x] files_external: 1.16.1
- [x] files_pdfviewer: 2.5.0
- [x] files_rightclick: 1.3.0
- [x] files_sharing: 1.16.2
- [x] files_trashbin: 1.14.0
- [x] files_versions: 1.17.0
- [x] files_videoplayer: 1.13.0
- [x] firstrunwizard: 2.13.0
- [x] logreader: 2.9.0
- [x] lookup_server_connector: 1.12.0
- [x] nextcloud_announcements: 1.13.0
- [x] notes: 4.3.1
- [x] notifications: 2.12.0
- [x] oauth2: 1.12.0
- [x] password_policy: 1.14.0
- [x] photos: 1.6.0
- [x] privacy: 1.8.0
- [x] provisioning_api: 1.14.0
- [x] recommendations: 1.3.0
- [x] serverinfo: 1.14.0
- [x] settings: 1.6.0
- [x] sharebymail: 1.14.0
- [x] support: 1.7.0
- [x] survey_client: 1.12.0
- [x] systemtags: 1.14.0
- [x] tasks: 0.14.4
- [x] text: 3.5.1
- [x] theming: 1.15.0
- [x] twofactor_backupcodes: 1.13.0
- [x] twofactor_totp: 6.3.0
- [x] updatenotification: 1.14.0
- [x] user_status: 1.4.0
- [x] viewer: 1.8.0
- [x] weather_status: 1.4.0
- [x] workflowengine: 2.6.0

**Comment by mziech** [comment]
Thanks for the report!

It seems to be caused by https://github.com/nextcloud/server/pull/31679 ... Oracle DB support. The fix is to either reduce the column length to 4000 or drop Oracle support ... 4000 chars should be more than enough, though.

**Comment by mziech** [comment]
I reduced the length of `service` (callback URL) to 2000 characters, should be enough.
